fix: issues introduced with new linter version (#1150)
```txt
"/home/runner/work/cortex/cortex/bin/golangci-lint" run --fix
Error: internal/scheduling/nova/external_scheduler_api.go:137:2: G404: Use of weak random number generator (math/rand or math/rand/v2 instead of crypto/rand) (gosec)
Error: internal/knowledge/datasources/plugins/openstack/controller_test.go:34:10: unusedwrite: unused write to field Monitor (govet)
Error: internal/knowledge/datasources/plugins/prometheus/controller_test.go:35:10: unusedwrite: unused write to field Monitor (govet)
Error: internal/scheduling/nova/cr_metrics_test.go:238:27: unusedwrite: unused write to field BasePipelineController (govet)
Error: internal/scheduling/reservations/commitments/reservation_controller.go:203:22: SA1019: (sigs.k8s.io/controller-runtime.Result).Requeue is deprecated: Use `RequeueAfter` instead.
```


- added //nolint:gosec to the rand.Shuffle call (non-crypto shuffle,
safe to suppress)
- removed Monitor: datasources.Monitor{} zero-value assignment
- removed Monitor: datasources.Monitor{} zero-value assignment
- replaced embedded composite literal with controller.Client =
fakeClient after struct creation
- replaced Requeue: true with RequeueAfter: time.Millisecond
(effectively immediate, non-deprecated)

---------

Signed-off-by: Markus Wieland <markus.wieland@sap.com>